// This is our AppController interface. Everything declared here is used in our template
interface IAppController extends ng.IController {
    toggle(): void; // toggle for the sidemenu
    save(): void; // dummy function for our save button in our template
    username: string; // username to be bind in our view
}

// This is our AppController. It has to implement everything declared in IAppController
export class AppController implements IAppController {

    // inject all services etc. Beware of the order in the constructor. You will need this to work with minification/obfuscation
    static $inject = ['$mdSidenav']; 

    constructor(private $mdSidenav: ng.material.ISidenavService) {
        // private marked elements in constructor are mapped to private fields in this class
    }

    // This is our public variable. You may want to initialize this field in the constructor
    public username: string = "Tom";

    public toggle(): void {
        // toggle function uses the $mdSidenav field generated by the constructor
        this.$mdSidenav('menu-left').toggle();        
    }

    public save(): void {        
        // window is a global variable - so just use them whereever you want
        window.alert("Hello from AppController!");
    }
}